FrontEnd PR
TamaraDimov/vespa-rentals-frontend pull request #18
Opened 2023-10-03 10:21 UTC by TamaraDimov

2023-10-03 13:46 UTC, Meltrust requested changes
Hi @TamaraDimov,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Nice code organization ✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-10-03 13:46 UTC, Meltrust commented on src/App.js
> +function App() {
- [ ] When I add a motorcycle, and then go to the "Models" section, the motorcycle is not showing on my end:

![image](https://github.com/TamaraDimov/vespa-rentals-frontend/assets/57421823/27d8d1a5-f52a-461c-baf2-cc4f82c7d7a8)

Browser console:

![image](https://github.com/TamaraDimov/vespa-rentals-frontend/assets/57421823/767d9389-6857-4691-9b55-756fa38dd2c5)

Rails console:

![image](https://github.com/TamaraDimov/vespa-rentals-frontend/assets/57421823/b1ca74dd-5d98-4a3f-92e0-fe8636b7a81f)

This may be working on your end because you have your local storage already populated with the correct values, but not for a brand new user.

Therefore, in order to correctly debug this issue, I suggest to either wipe your browser's localStorage, or using an incognito tab.

Kindly, fix this issue so the motorcycles can be shown on the homepage.  👍 

_note:  For your info, the models DO show on the "Delete motorcycle" page._

2023-10-03 13:46 UTC, Meltrust commented on src/App.js
> +function App() {
- [ ] When I go to the "Delete Motorcycle" page, the frontend enters an endless loop of requests to the server:

![image](https://github.com/TamaraDimov/vespa-rentals-frontend/assets/57421823/95d9b55b-6187-4d9a-af72-2f71c387e630)

In order for it to stop, I need to get out of the "Delete Motorcycle" section.

Most likely, this `useEffect` hook needs to be corrected:

![image](https://github.com/TamaraDimov/vespa-rentals-frontend/assets/57421823/eef3fedc-4cab-45ad-8df1-eb309c7559aa)


Kindly, make it so the motorcycles are fetched only once when a user visits that section of your project.

- [ ] Most likely due to the previous issue, the "Delete" button does not work, preventing me from deleting motorcycles.

Kindly fix this issue so your users can delete motorcycles.  👍

2023-10-03 13:46 UTC, Meltrust commented on src/App.js
> +function App() {
- [ ] In the mobile view, the I couldn't find a way to collapse or close the sidebar:

![image](https://github.com/TamaraDimov/vespa-rentals-frontend/assets/57421823/f44e0946-3e9e-4ba5-9b20-ef6e872377d8)

This makes the mobile view not very usable.  Kindly make it so there is a way to collapse or hide it so your users can get more access to the content. 👍

2023-10-03 13:46 UTC, Meltrust commented on src/App.js
> +function App() {
- [ ]  Please, kindly refactor this main "app" functional component to ES6 arrow function, so your code complies with the latest standards.

Refactoring is easy:

```javascript
const App = () => {
  // ...
}
```

## Explanation

The `function` keyword has been soft deprecated in almost all the software industry in favor of ES6 arrow functions. This means, almost nobody uses it anymore, so much that it's considered a non-best practice.

- [ ] OPTIONAL: Refactor the rest of the functions.

You can do a search in Vscode for the "function" word, and correct as needed.  Shouldn't take you more than 5-10 min so don't worry (I found ~10):  

![image](https://github.com/TamaraDimov/vespa-rentals-frontend/assets/57421823/5dc0bafc-c942-406a-b136-10a38bc2e550)

That way, your code will meet the latest standards. 💪

2023-10-03 13:46 UTC, Meltrust commented on README.md
> +- [Microverse](https://www.microverse.org/)
- [ ] Kindly, give proper credit to the design's author, as stated in the project [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md).

2023-10-03 13:55 UTC, kifle23 commented
On behalf of the team, thank you @Meltrust for your thorough review. 🙏🏻

2023-10-04 20:45 UTC, Meltrust approved these changes
#### Hi @TamaraDimov,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)




Cheers and Happy coding!👏👏👏


------

2023-10-04 20:48 UTC, kifle23 commented
Thank you so much @Meltrust 🙏🏻

2023-10-04 20:49 UTC, Besufekad-HAZ commented
@Meltrust Thank you for your valuable code review! Your feedback has greatly improved our work. 👍🏾 💯

2023-10-05 09:16 UTC, merged